### ISSUE TITLE
bpmn is driven through for temporal

### ISSUE THREAD

**Issue by cq-z** [nitram509/lib-bpmn-engine#143]
@nitram509 hi ，Are you considering using [temporal](https://docs.temporal.io/) to drive bpmn。Make lib-bpmn-engine a distributed service。

**Comment by cq-z** [comment]
like this 
![image](https://github.com/nitram509/lib-bpmn-engine/assets/3038490/4eeb63a2-5b5d-479c-8835-64f684da5156)

**Comment by nitram509** [comment]
Hi,

no, I'm not considering using temporal.
lib-bpmn-engine is meant to be embedded into applications as a library.

That said, because of its nature lib-bpmn-engine could be used in a temporal application, and then use cases which required distributed execution are possible to implement.

Regards
Martin

**Comment by cq-z** [comment]
I'll try it out when this feature（#12） is complete

**Comment by cq-z** [comment]
thanks
